# Generated by Django 2.2.3 on 2019-07-26 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HantorismUser',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('PW', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('studentNum', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=8)),
                ('email', models.CharField(max_length=20)),
                ('isHantor', models.CharField(choices=[('hantor', 'YES'), ('no_hantor', 'NO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HantorismPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_hantorism.HantorismUser')),
            ],
        ),
    ]
