# Generated by Django 2.2.3 on 2019-07-30 13:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('common_hantorism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hantorismuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='hantorismuser',
            name='studentNum',
            field=models.CharField(max_length=10),
        ),
    ]
