# Generated by Django 2.2.4 on 2019-08-22 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common_hantorism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HantorismBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('book_rent_state', models.BooleanField(default=False)),
                ('book_owner_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HantorismRentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_hantorism.HantorismUser')),
                ('rent_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_hantorism.HantorismBook')),
            ],
        ),
        migrations.DeleteModel(
            name='HantorismLibrary',
        ),
    ]
