# Generated by Django 2.2.3 on 2019-08-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_hantorism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hantorismuser',
            name='isHantor',
            field=models.CharField(choices=[('hantor', 'YES'), ('no_hantor', 'NO')], max_length=12, null=True),
        ),
    ]
