# Generated by Django 2.2.4 on 2019-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_hantorism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hantorismuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
