# Generated by Django 2.2.4 on 2019-08-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_hantorism', '0002_hantorismuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hantorismrentbook',
            name='return_request',
            field=models.BooleanField(default=False),
        ),
    ]
